apiVersion: v1
kind: Service
metadata:
  name: predictive-alpha-api
spec:
  selector:
    app: predictive-alpha-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
